package com.example.app.wishlist.data.db

import android.content.Context
// NOTE: MyObjectBox is generated by the ObjectBox Gradle plugin/kapt at build time —
// it won't exist (and this import will show red) until you've built at least once.
// By default it's generated in the common package of your @Entity classes. With only
// one entity (Product, in data.db.entity) that's this package. If you add entities in
// other packages later and this import breaks, either move it back to the common
// package or pin the location explicitly via the `objectbox { myObjectBoxPackage(...) }`
// block in app/build.gradle.kts, then update this import to match.
import com.example.app.wishlist.data.db.entity.KgEdge
import com.example.app.wishlist.data.db.entity.KgNode
import com.example.app.wishlist.data.db.entity.MyObjectBox
import com.example.app.wishlist.data.db.entity.Product
import io.objectbox.Box
import io.objectbox.BoxStore
import timber.log.Timber

/**
 * Provider for ObjectBox database access.
 *
 * ObjectBox is used for:
 * - Fast, efficient product storage
 * - Semantic search with full-text indexing
 * - Complex filtering and sorting
 * - On-device only (no cloud)
 *
 * Thread-safe singleton pattern.
 */
object ObjectBoxProvider {

    private const val TAG = "ObjectBoxProvider"

    private var boxStore: BoxStore? = null
    private var productBox: Box<Product>? = null
    private var kgNodeBox: Box<KgNode>? = null
    private var kgEdgeBox: Box<KgEdge>? = null

    /**
     * Initialize ObjectBox database.
     * Call this once during app startup (in Application class or MainActivity).
     */
    fun initialize(context: Context) {
        try {
            if (boxStore != null) {
                Timber.d("ObjectBox already initialized")
                return
            }

            boxStore = MyObjectBox.builder()
                .androidContext(context.applicationContext)
                .name("wishlist-db")
                .build()

            productBox = boxStore?.boxFor(Product::class.java)
            kgNodeBox = boxStore?.boxFor(KgNode::class.java)
            kgEdgeBox = boxStore?.boxFor(KgEdge::class.java)
            Timber.d("ObjectBox initialized successfully")
            logDatabaseStats()
        } catch (e: Exception) {
            Timber.e(e, "Failed to initialize ObjectBox")
            throw e
        }
    }

    /**
     * Get the product box for database operations.
     */
    fun getProductBox(context: Context): Box<Product> {
        if (boxStore == null) {
            initialize(context)
        }
        return productBox ?: throw IllegalStateException("ProductBox not initialized")
    }

    /**
     * Knowledge-graph nodes. All graph writes should go through the graph repository
     * rather than touching this box directly — resolve-before-create and one
     * transaction per ingestion batch are invariants the box itself cannot enforce.
     */
    fun getKgNodeBox(context: Context): Box<KgNode> {
        if (boxStore == null) {
            initialize(context)
        }
        return kgNodeBox ?: throw IllegalStateException("KgNodeBox not initialized")
    }

    /** Knowledge-graph edges. See [getKgNodeBox] on writing through the repository. */
    fun getKgEdgeBox(context: Context): Box<KgEdge> {
        if (boxStore == null) {
            initialize(context)
        }
        return kgEdgeBox ?: throw IllegalStateException("KgEdgeBox not initialized")
    }

    /**
     * Get the BoxStore instance.
     */
    fun getBoxStore(context: Context): BoxStore {
        if (boxStore == null) {
            initialize(context)
        }
        return boxStore ?: throw IllegalStateException("BoxStore not initialized")
    }

    /**
     * Close the database connection.
     * Call this during app shutdown or when needed.
     */
    fun close() {
        try {
            boxStore?.close()
            boxStore = null
            productBox = null
            kgNodeBox = null
            kgEdgeBox = null
            Timber.d("ObjectBox closed")
        } catch (e: Exception) {
            Timber.e(e, "Error closing ObjectBox")
        }
    }

    /**
     * Check if ObjectBox is initialized.
     */
    fun isInitialized(): Boolean = boxStore != null

    /**
     * Log database statistics (for debugging).
     */
    private fun logDatabaseStats() {
        try {
            val sizeBytes = boxStore?.dbSizeOnDisk ?: 0L
            Timber.d("Database file size: $sizeBytes bytes")
        } catch (e: Exception) {
            Timber.e(e, "Error logging database stats")
        }
    }

    /**
     * Clear all data from the database.
     * WARNING: This is irreversible!
     */
    fun clearAllData(context: Context) {
        try {
            getProductBox(context).removeAll()
            getKgEdgeBox(context).removeAll()
            getKgNodeBox(context).removeAll()
            Timber.w("All data cleared from ObjectBox!")
        } catch (e: Exception) {
            Timber.e(e, "Error clearing database")
        }
    }

    /**
     * Export database statistics.
     * Useful for debugging and optimization.
     */
    fun getDatabaseStats(context: Context): DatabaseStats {
        return try {
            val box = getProductBox(context)
            val productCount = box.count()
            val sizeBytes = boxStore?.dbSizeOnDisk ?: 0L

            DatabaseStats(
                productCount = productCount,
                databaseSizeBytes = sizeBytes,
                lastAccess = System.currentTimeMillis()
            )
        } catch (e: Exception) {
            Timber.e(e, "Error getting database stats")
            DatabaseStats()
        }
    }

    data class DatabaseStats(
        val productCount: Long = 0,
        val databaseSizeBytes: Long = 0,
        val lastAccess: Long = 0
    )
}
